Session Updated & Tickets Link
src-d/talks pull request #50
Opened 2017-05-25 15:47 UTC by margaridag

2017-05-25 15:48 UTC, margaridag commented
I think it conflicts with the "Soon!" you wrote on the button :(

2017-05-26 10:43 UTC, erizocosmico requested changes

2017-05-26 10:43 UTC, erizocosmico commented on front-2017/_data/sessions.yml
> +  description: "One of the must-haves for any compile-to-JS language, such as Elm, is the interoperability with JavaScript. In this talk, we'll explore how Elm communicates with JavaScript and why th
s/choices - that/choices that/

2017-05-26 14:22 UTC, erizocosmico approved these changes

2017-05-26 14:22 UTC, merged